### ISSUE TITLE
not working with FAN (Centos 5.11)

### ISSUE THREAD

**Issue by xila76** [gorantornqvist/nagios-plugins#6]
I tried this plugin with my installation of nagios (with FullyAutomatedNagios aka FAN) but it doesn't work, what is the version of python needed?

**Comment by gorantornqvist** [comment]
I´ve tested it with Python 2.6 .
Do you get any error messages?

What happens if you log on by SSH to your nagios host and run the script manually, e.g.
./check_freenas.py -H 192.168.X.X -u root -p myrootpassword -t alerts

**Comment by xila76** [comment]
I think in FAN it's python 2.4...

When I launch command :

Traceback (most recent call last):
  File "./check_freenas.py", line 35, in ?
    import requests
  File "/usr/lib/python2.4/site-packages/requests/__init__.py", line 53
    from .packages.urllib3.contrib import pyopenssl
         ^
SyntaxError: invalid syntax


I've manually setup json and argparse, for requests I can't use easy_install or pip but after copying as I seen here http://stackoverflow.com/questions/17309288/importerror-no-module-named-requests the error about missing requests stop... but the previous error still remain...

**Comment by gorantornqvist** [comment]
Hmmm, strange error.
I´m running centos and I´m using this rpm package and not pip:

[root@host ~]# yum info python-requests
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
Installed Packages
Name        : python-requests
Arch        : noarch
Version     : 2.6.0
Release     : 3.el6
Size        : 344 k
Repo        : installed
From repo   : centos-base
Summary     : HTTP library, written in Python, for human beings
URL         : http://pypi.python.org/pypi/requests
License     : ASL 2.0
Description : Most existing Python modules for sending HTTP requests are extremely verbose and
            : cumbersome. Python’s built-in urllib2 module provides most of the HTTP
            : capabilities you should need, but the API is thoroughly broken. This library is
            : designed to make HTTP requests easy for developers.

**Comment by xila76** [comment]
On my CentOS 5.11 i686 : 

[root@nagios ~]# yum info python-requests
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: mirror.ibcp.fr
 * epel: epel.mirrors.ovh.net
 * extras: mirror.ate.info
 * updates: miroir.univ-paris13.fr
14 packages excluded due to repository priority protections
Error: No matching Packages to list

**Comment by gorantornqvist** [comment]
Hi,
On EL5 its called python26-requests and you can find it in the EPEL repo:
https://dl.fedoraproject.org/pub/epel/5/i386/repoview/python26-requests.html

**Comment by xila76** [comment]
Ok, I've remove my folder that contains requests from site-package in my python
Now I've setup the python26-requests

But it's still does not work : 
[root@nagios plugins]# ./check_freenas.py -H 192.168.1.12 -u root -p password -t alerts
Traceback (most recent call last):
  File "./check_freenas.py", line 35, in ?
    import requests
ImportError: No module named requests

I've changed the first line of the plugin for force to use python26, after that it tell me he need argparse... I've setting up argparse with yum python26-argparse... ok...

And now...

[root@nagios plugins]# ./check_freenas.py -H 192.168.1.12 -u root -p password -t alerts
UNKNOWN - Error when contacting freenas server: (<type 'exceptions.TypeError'>, TypeError("'NoneType' object is not iterable",), <traceback object at 0xb7b24734>)

:cry:

**Comment by gorantornqvist** [comment]
A bit of a late reply (why doesnt github send e-mails when someone posts...)

Can you access http://freenas/api/v1.0/system/alert/?format=json using "root" and your password?

**Comment by xila76** [comment]
for the moment no...

<code>
An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.
</code>

but i think it's because it's virtual freenas who have not lot of RAM I know this but it's only for an iSCSI LUN of backup I've set it, only for work when another iSCSI LUN bay need to reboot/upgrade firmware...

that's why it's not really important... in my infrastructure to have a monitoring of this freenas but for a better integration of nagios and freenas in my infrastructure it's better if it's can work
Could you send me a sample information of what's this url "normally" respond ?

sorry for me poor english... i'm french... =)

**Comment by gorantornqvist** [comment]
So that is your problem.
That url is the one that the nagios check uses and it should return some json data and not the error you receive.
